export enum Repository {
  USER_REPOSITORY = 'USER_WALLET_REPOSITORY',
  TOKEN_REPOSITORY = 'TOKEN_REPOSITORY',
  SWAP_HISTORY_REPOSITORY = 'SWAP_HISTORY_REPOSITORY',
  TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY'
}

export enum Connection {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  ETHEREUM_CONNECTION = 'ETHEREUM_CONNECTION',
  BSC_CONNECTION = 'BSC_CONNECTION'
}
